import { test, expect, 开一段临时会话, 等进了对话, 进坞 } from './fixtures.js'
import { mkdirSync } from 'node:fs'
const suggestion = '检查缺失值并说明处理方法'
test('灰色建议不是草稿；Enter 不接受，Tab 接受后才可发送', async ({ dawn }) => {
  const { page } = dawn
  await 开一段临时会话(page)
  await 等进了对话(page)
  const input = page.locator('.composer-field').first()
  await input.fill('帮我看看数据')
  await input.press('Enter')
  await expect(input).toHaveAttribute('data-ghost', 'true')
  await expect(input).toHaveValue('')
  await expect(input).toHaveAttribute('placeholder', suggestion)
  const turns = await page.locator('.turn').count()
  await input.press('Enter')
  await expect(input).toHaveValue('')
  await expect(page.locator('.turn')).toHaveCount(turns)
  await input.focus()
  const color = await input.evaluate((el) => getComputedStyle(el, '::placeholder').color)
  expect(color).not.toBe('rgba(0, 0, 0, 0)')
  mkdirSync('tmp/next-prompt-verification', { recursive: true })
  await page.mouse.move(1000, 300)
  await page.screenshot({ path: 'tmp/next-prompt-verification/ghost.png' })
  await input.press('Tab')
  await expect(input).toHaveValue(suggestion)
  await expect(input).not.toHaveAttribute('data-ghost', 'true')
  await page.screenshot({ path: 'tmp/next-prompt-verification/accepted.png' })
  await input.fill('我的新问题')
  await input.press('Tab')
  await expect(input).toHaveValue('我的新问题')
})

test('侧边对话独立显示建议，接受不改变主区草稿', async ({ dawn }) => {
  const { page } = dawn
  await 开一段临时会话(page)
  await 等进了对话(page)
  const main = page.locator('main.main .composer-field')
  await main.fill('主区草稿')
  await 进坞(page, '对话')
  const dock = page.locator('aside.right-dock')
  await dock.getByRole('button', { name: '另开一段', exact: true }).click()
  const input = dock.locator('.composer-field')
  await input.fill('看看数据')
  await input.press('Enter')
  await expect(input).toHaveAttribute('data-ghost', 'true')
  await input.press('Tab')
  await expect(input).toHaveValue(suggestion)
  await expect(main).toHaveValue('主区草稿')
})
