/** Generate app and template tray PNGs from the approved font-independent RP mark. */
import { app, BrowserWindow } from "electron"
import { readFileSync, writeFileSync } from "node:fs"

const source = readFileSync(new URL("../packaging/rp-mark.svg", import.meta.url), "utf8")
const paths = source.match(/<path\b[^>]*\/>/g).join("\n")
const monochrome = paths.replace(/fill="#[a-f0-9]+"/g, 'fill="#000000"')
const appSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<rect x="64" y="64" width="896" height="896" rx="200" fill="#08213f"/>
<g transform="translate(146 274) scale(1.19)">${paths}</g></svg>`
const traySvg = `<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 36 36">
<g transform="translate(1 7) scale(.055)">${monochrome}</g></svg>`
writeFileSync("packaging/icon.svg", appSvg + "\n")
writeFileSync("packaging/tray-icon.svg", traySvg + "\n")

async function render(svg, size) {
  const win = new BrowserWindow({ show: false, width: size, height: size,
    transparent: true, backgroundColor: "#00000000",
    webPreferences: { offscreen: true } })
  try {
    await win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(`<html><body style="margin:0;background:transparent">${svg}</body></html>`)}`)
    const image = await win.webContents.capturePage({ x: 0, y: 0, width: size, height: size })
    return image.resize({ width: size, height: size }).toPNG()
  } finally {
    win.destroy()
  }
}

app.on("window-all-closed", () => {}) // Keep the process alive between the two renders.
app.whenReady().then(async () => {
  writeFileSync("packaging/icon.png", await render(appSvg, 1024))
  const tray = await render(traySvg, 36)
  writeFileSync("packaging/tray-icon.png", tray)
  writeFileSync("src/electron/tray-icon.ts", `// Generated by npm run make-icon from packaging/rp-mark.svg; transparent macOS template image.\nexport const 托盘图标 = "data:image/png;base64,${tray.toString("base64")}"\n`)
  console.log("Generated RP app icon (1024²) and transparent tray icon (36²).")
}).catch((error) => {
  console.error(error)
  app.exit(1)
}).finally(() => app.quit())
